### ISSUE TITLE
Bug and Issues for 1.19.4

### ISSUE THREAD

**Issue by lenugre** [SolipIngen/minecraft.progressivearchery#30]
Hey there, i've tried out your mod for 1.19.4 and ran into some issues and wanted to let you now, since i really like the overall concept of the mod:

- The fletching table didn't seem to work for me, which made me unable to craft any arrows. REI also didn't show a recipe for any of the arrow types 

- The copper nuggets overlapped with the copper nuggets from the mod "Extended Copper" which made one type of copper nuggets only available through the crative menu.

Tested version:1.5

**Comment by SolipIngen** [comment]
Thanks for writing in. In response to your points:

- How does the Fletching Table not work for you (does the Fletching screen not show up, cannot put ingredients into slots etc.)? Depending on what's happening, the solution will be different. As for REI, Progressive Archery is still in beta, and REI integration has not been implemented yet, though it is planned.
- Which copper nugget was the one showing up? As the two Copper Nuggets should have different identifiers, they should be registered as distinct objects. Of course, as the Progressive Archer Copper Nugget is only there for crafting Copper Arrows, I might consider making this mod dependent on Extended Copper, once I take a look at Extended Copper myself.

**Comment by SolipIngen** [comment]
Update: Copper nuggets and other arrow head ingredients have now been replaced with craftable Arrowheads as of v0.1.9. This should resolve potential conflicts with other mods that introduce copper nuggets, as Progressive Archery no longer has copper nuggets as an item.
