### ISSUE TITLE
How do you get horse hair?

### ISSUE THREAD

**Issue by TheSpiderDungeon** [SolipIngen/minecraft.progressivearchery#49]
How do you even get horse hair? I checked the mod page. "Uniquely obtained" means a whole lotta nothin' lol

REI isn't very helpful either, unfortunately.

**Comment by SolipIngen** [comment]
You use shears on tamed Horses (and Striders for Striderhair). Horses need to "eat grass" (i.e. do the animation in which they bend their heads towards the ground) to "regrow" their hair once sheared. Striders regrow their hair over time, and they will regrow their hair faster when out of lava.
Hoglinhair is not obtained with shears, and can be obtained only via a special method. A clue is given in the wording of the advancement related to Hoglinhair (visible once Horsehair and Striderhair are obtained). Another hint is that it is somewhat related to how you get the Monsters Hunted advancement. The method is intentionally undisclosed, though I am happy to answer if asked directly.

If you downloaded the mod on CurseForge, please post any further questions related to mod content on the comments section of the mod page. This Issues page is for specifically technical issues, such as crashes or bugs.
