### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by SaraXianLin** [SolipIngen/minecraft.progressivearchery#50]
The Game crashes when just joining a world.

Minecraft version 1.20.1
Fabric 
Mod: 1.1.3-1.20.1+trinkets

[crash-2023-10-11_22.34.39-client.txt](https://github.com/SolipIngen/minecraft.progressivearchery/files/12877176/crash-2023-10-11_22.34.39-client.txt)

**Comment by SolipIngen** [comment]
Hello. Apologies for the delayed update.
This should have been fixed with v1.1.3.a-1.20.1 & v1.1.3.a-1.20.1+trinkets. Please check, and feel free to open a new Issue if it still persists.
