### ISSUE TITLE
LevelZ compat

### ISSUE THREAD

**Issue by Feliks-WR** [SolipIngen/minecraft.progressivearchery#52]
https://modrinth.com/mod/levelz
Currently, I am able to use this mod's bows at lvl 0 archery.

**Comment by SolipIngen** [comment]
Hello. The level requirement issue should be fixable on your end with a custom Data Pack for Progressive Archery items. Consider re-working the example Data Pack in https://github.com/Globox1997/LevelZ/tree/1.20/exampleDatapack, plugging in your desired level thresholds and mod items as "progressivearchery:[item name]" for all newly added bows and "minecraft:bow" for the original bow. As an example, "minecraft:bow" can have a level value of 1, "progressivearchery:horn_bow" with level 2, "progressivearchery:diamond_fused_tubular_bow" with level 20, etc.
As for the additional damage bonus per level, unfortunately there are currently no plans for the required code-wise integration with this mod. I decided against a levelling system affecting damage output in this mod, as I believe growth in player skill should be sufficient for an enjoyable progressive experience with the bow variants. Thus, with the aforementioned Data Pack, you should be able to set from which level you can start using the bows, but the level value does not affect damage output.
I am happy to discuss this separately with all players, but for now I will close this Issue.
