### ISSUE TITLE
Vanilla Leads don't get dropped back

### ISSUE THREAD

**Issue by 1Bulgarian** [SolipIngen/minecraft.progressivearchery#55]
Whenever you leash an animal and unleash it right after, the lead doesn't get dropped. This isn't the case with the fireproof lead, everything is fine there. I really hate this "feature" and can you show me how to fix it.

Tested through my 100 mods modpack just to find this issue from here, I really want to change it to be vanilla behaviour.

**Comment by SolipIngen** [comment]
Hello, thank you for writing in.
This issue should have been resolved with the latest v1.1.5-1.20.4 updates.
Please feel free to submit another Issue if the problem persists.
