### ISSUE TITLE
about Archer villager.

### ISSUE THREAD

**Issue by tense11** [SolipIngen/minecraft.progressivearchery#59]
Which hostile creatures can Archer attack? I just tried it, and it seems that it won’t attack Piglin Brute after being taken to the nether world.

**Comment by SolipIngen** [comment]
Thank you for playing Progressive Archery.
Archer villagers are hostile towards mobs that are hostile towards villagers: Zombie variants (excluding Zombiefied Piglins), Illagers, and Witches. For other mobs, they do not target them without provocation.
