### ISSUE TITLE
1.21 [BUG] translation error and arrows hitting on top.

### ISSUE THREAD

**Issue by makumaku1974** [SolipIngen/minecraft.progressivearchery#71]
![image](https://github.com/user-attachments/assets/3d75e032-ecb2-4825-8b0a-6646f6516447)

**Comment by SolipIngen** [comment]
Thank you for writing in.

The translation issue should be easy to fix, you can expect it to be fixed in the next mod update.

As for the arrows, please let me know how it happens. Specifically, please let me know:
1. When and how does this bug happen?
2. What other mods do you have installed?
3. Does the game log show anything unusual? If it does, please upload it here.

**Comment by makumaku1974** [comment]
> Thank you for writing in.
> 
> The translation issue should be easy to fix, you can expect it to be fixed in the next mod update.
> 
> As for the arrows, please let me know how it happens. Specifically, please let me know:
> 
> 1. When and how does this bug happen?
> 2. What other mods do you have installed?
> 3. Does the game log show anything unusual? If it does, please upload it here.

This bug is actually caused by fresh animations.... sorry for the bother. I think the translations only need fixing at this point.

**Comment by SolipIngen** [comment]
No problem. It is odd, though -- I myself test the mods with Fresh Animations through Custome Entity Models, and I have not seen this happen before.

Is Fresh Animations the only resource pack you've had enabled? Or perhaps some other adjacent resource pack?

**Comment by makumaku1974** [comment]
Only Fresh Animations. The Head area of Fresh Animation seems to teleport the arrows above the head. I installed another version of Fresh Animation where the head animations are disabled and problem is gone. It seems that the reourcepack is in beta and the devs where creating it for visual testing. will be closing this now.

**Comment by makumaku1974** [comment]
Please make sure if other people used Fresh Animations with your mod in 1.21 just reference this post. It might give them the idea about it and why it happens.
