### ISSUE TITLE
Laggy Arrows

### ISSUE THREAD

**Issue by MagicianDC** [SolipIngen/minecraft.progressivearchery#79]
Players are shooting too much Iron arrows all over my server and lagging it. How do I delete them through commands? I used the vanilla one but it only deletes vanilla arrows. Any help?

**Comment by SolipIngen** [comment]
Hello. 

I suspect you that you're trying to call `minecraft:arrow` and depsawn them. 
If you haven't yet, you should instead use `progressivearchery:iron_arrow`, the entity identifier for Iron Arrows. Follow the same format to address any other modded arrow in a command, e.g. Golden Kid Arrows are called `progressivearchery:golden_kid_arrow`.

Note that Tipped (Kid) Arrows are not a separate entity -- entity-wise, they are just Golden (Kid) Arrows as well.

Please close this Issue if this has resolved your problem.

**Comment by MagicianDC** [comment]
Thank you for your quick response. The command I'm using is:

/kill @e[type=arrow]

Where would I add "progressivearchery:iron_arrow"?

Thank you.
